### ISSUE TITLE
Error with MySQL-python when installin requirements

### ISSUE THREAD

**Issue by luciano-fiandesio** [LINKIWI/orion-server#1]
`> make bootstrap`

`pip install -r requirements.txt`
...
```
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 16))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-M8U2wF/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found`
```

**Comment by luciano-fiandesio** [comment]
The error goes away if I install:

`apt-get install libmysqlclient-dev`

**Comment by LINKIWI** [comment]
That is the correct solution; I forgot to document this in the README. I'll patch soon.
